# Generated by Django 2.0.1 on 2018-03-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=280, null=True)),
                ('device_id', models.IntegerField(unique=True)),
                ('device_name', models.CharField(max_length=280)),
                ('href', models.URLField()),
                ('model_name', models.CharField(max_length=280, null=True)),
                ('vendor_identifier', models.IntegerField(null=True)),
                ('vendor_name', models.CharField(max_length=280, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('object_id', models.CharField(max_length=140)),
                ('object_instance', models.IntegerField()),
                ('object_name', models.CharField(max_length=280)),
                ('object_type', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacnet_listener.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('present_value', models.FloatField()),
                ('permanent', models.BooleanField(default=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacnet_listener.Object')),
            ],
        ),
    ]
