# Generated by Django 2.0.1 on 2018-03-08 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bacnet_listener', '0002_auto_20180308_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacnet_listener.Timestamp'),
        ),
    ]
